version: 2
image: ubuntu:18.04
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Setup docker
          command: |
            make up-ci
      - run:
          name: Test code
          command: docker exec -it sandbox-app vendor/bin/phpunit

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
